# Generated by Django 5.1.5 on 2025-04-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='description',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
